# Generated by Django 5.2.14 on 2026-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_company_sync_metadata_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения'),
        ),
    ]
